docker:
  compose:
    fileName: docker-compose.yml
    version: "3.9"
    defaultServicePort: 8081
    springProfile: local
    springDefaultPort: 8080
git:
  checkurl:
  sshkey:
    location: .ssh
    passphrase: tbd
file:
  location: /tmp
angular:
  template:
    name: template
    repo: tbd
    branch: main
    module-names:
      ui: template-ui
      api: template-api
react:
  template:
    name: template
    repo: tbd
    branch: main
    module-names:
      ui: template-ui
      api: template-api
spring:
  template:
    name: template
    repo: git@github.com:cleverpine/spring-template.git
    branch: base
    module-names:
      service: template-service
      api: template-api
quarkus:
  template:
    name: template
    repo: tbd
    branch: main
    module-names:
      service: template-service
      api: template-api
cloudconfig:
  image: tbd
  container-name: tbd
  port: 8888
  encrypt-key: tbd
  user: tbd
  password: tbd
  folder: tbd